include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    depend_on_referenced_packages: ignore
    unused_field: ignore
    use_build_context_synchronously: ignore
    use_super_parameters: ignore ignore ignore
