name: permit_inout
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.0
  flutter_lints: ^5.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.18
  flutter_launcher_icons: "^0.14.2" # Make sure this is under dev_dependencies

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/logo_app.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/logo_app.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/login.png
    - assets/icons/background.png
